name: Build website

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Setup NPM 7
        run: npm install -g npm@7

      - name: Check cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build website
        run: npm run build
